language: node_js
node_js:
  - '0.8'
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-django-app' ]; then cd .. && eval "mv $currentfolder generator-django-app" && cd generator-django-app; fi

